version: 0.0
os: linux

files:
  - source: /target/swe699-hgmtrebing.jar
    destination: /target/

hooks:
  ApplicationStop:
    - location: scripts/prepare.sh
      timeout: 60

  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120