version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - tar cvf build.tar target/swe699-hgmtrebing.jar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/swe699-hgmtrebing.jar
    - build.tar